language: android
jdk: oraclejdk8
sudo: false
before_install:
- yes | sdkmanager "platforms;android-27"
android:
  components:
    - android-27
    - build-tools-27.0.3
    - extra
    - addon
    - sys-img-armeabi-v7a-android-27
before_script:
  - echo no | android create avd --force -n testEmulator -t android-27 --abi armeabi-v7a
  - emulator -avd testEmulator -no-skin -no-audio -no-window &
  - android-wait-for-emulator
script:
  - ./gradlew test